### PR TITLE
feat: drop support for php 8

### PR DESCRIPTION
**Pull request by Chris53897**
allow PHPUnit 10/11,
allow "spatie/phpunit-snapshot-assertions" 5

superseeds #156 and #153

### CODE REVIEW

**Comment by DASPRiD** [comment]
LGTM!

**Comment by DASPRiD** [comment]
Could you squash your commits down to a single commit, so I can retain your authorship?

**Comment by Chris53897** [comment]
done

**Comment by Chris53897** [comment]
@DASPRiD Anything else i should do here?

**Pull request merged**
