### PR TITLE
Add GD Image backend

### PR DESCRIPTION
**Pull request by arxeiss**
My client's web hosting provider don't have support for Imagick, even though they are promising it will be added. 

I'm generating QR codes for payment, which is added into email body. And email client's do not have nice support for SVG. So I need old-school GD support.

However, GD has limited sets of functions. I believe, that it is OK, when that backend will have also limited sets of features.
So this is not supported:
- Any roundness like `DotsModule`, `RoundnessModule` or `SimpleCircleEye`
- Gradients

And because GD does not support Paths like Imagick or SVG do, I need to generate a bit different paths, so they are not so complex.

### CODE REVIEW

**Comment by DASPRiD** [comment]
Well, I can understand not supporting gradients through this backend, as that would require pixel-level control, which is extremely slow to do in PHP. Though general paths shouldn't be an issue:

A very primitive approach could use `imagefilledpolygon` and calculate a close enough approximation of points beforehand based on the given path, that would be possible with relatively simple calculations.

**Comment by arxeiss** [comment]
I was trying to do that, but I don't know how to solve subtraction. Because use have `EdgeIterator` and `getSimplifiedPoints` which returns path like this example below.

You have an outer path and inside is an inner path. And the inner one subtracts from the outer one. Look at this SVG

```svg
<svg viewBox="0 0 500 500" xmlns="http://www.w3.org/2000/svg">
  <path fill="#7e7e7e" fill-rule="evenodd" d="M131 55 L245 55 L245 154 L114 159 Z
    M169 79 L206 78 L206 121 L158 122 L169 79 Z"></path>
</svg>
```
Result will look like this

image

So I'm not sure how I would be able to use `imagefilledpolygon` because when I draw an outer path, it fills it completely. And then I would have to somehow delete the inner path. And those paths can intersect just partially. And there might be multiple nested paths.

If you know how to handle this with `imagefilledpolygon`, please give me some hint. Because that is what I was trying to do last 3 days.

**Comment by DASPRiD** [comment]
Maybe this might be of help (README states that he never finished the code for the path, but might be good guidance):

https://github.com/stefanak-michal/SvgRenderer/blob/master/Shapes.php#L318-L419

Maybe there are other libraries out there as well, who knows :)

**Comment by DASPRiD** [comment]
Here's another library which seems to be actually maintained:

https://github.com/meyfa/php-svg/tree/main/src/Rasterization/Path

**Comment by arxeiss** [comment]
PHP-SVG seems interesting. Will take a look at it, how and if it works.

**Comment by arxeiss** [comment]
So I did some checks and it seems promising.

However, latest release is `v0.11.3` (from February), which is failing to draw nested paths.
The latest master works better, all QR codes were OK. But there is minor issue with scaling.

So when they will release new version, I can rewrite that to use PHP-SVG library. 
I don't think that writing own rasterizer is a good idea. It is quite complex and it would require maintenance as well.

**Comment by DASPRiD** [comment]
An alternative would be to not use the ImageRenderer with all its features at all for GDLib, but implement a GDLibRenderer which doesn't have any styling support at all.

**Comment by arxeiss** [comment]
I see that PHP-SVG released new version couple of hours ago. I will check that.

But what you are suggesting might be better solution. Even I would integrate PHP-SVG, it would not support Gradients anyway.

**Comment by arxeiss** [comment]
I changed implementation including README. So no hacks across all files, but a completely new rendered is added. Please check it now. Thanks

**Comment by DASPRiD** [comment]
@arxeiss Excuse the extremely long wait. I'm preparing a new major release now. Could you adjust your PR to use PHP 8.1 features?

See changes introduced by #157

**Comment by arxeiss** [comment]
Closing in favor of #159

**Pull request closed without merging**
