### PR TITLE
Fix Unsupported operand types: string & int

### PR DESCRIPTION
**Pull request by askdkc**
need to fix `Unsupported operand types: string & int`

So I changed:
`$byte = $bytes[$i] & 0xff;`
to
`$byte = ord($bytes[$i]) & 0xff;`

### CODE REVIEW

**Comment by DASPRiD** [comment]
Isn't this a duplicate of #122?

**Comment by askdkc** [comment]
> Isn't this a duplicate of #122?

You are right.
Let me close my initial PR then😅

**Comment by DASPRiD** [comment]
@askdkc I'm currently preparing a new major release. Can you close all your PRs and make a single new PR without conflicts? :)

**Comment by askdkc** [comment]
@DASPRiD 

OK.

**Pull request closed without merging**
