### PR TITLE
Fix implicitly nullable params

### PR DESCRIPTION
**Pull request by kamil-tekiela**

### CODE REVIEW

**Comment by DASPRiD** [comment]
What exactly is wrong with that? Maybe @Chris53897 can shed some light here, since he introduced that.

**Comment by kamil-tekiela** [comment]
Oh sorry, I should have mentioned the reason. It's because of the deprecation in PHP 8.4. 

```
23) /home/runner/work/phpmyadmin/phpmyadmin/vendor/bacon/bacon-qr-code/src/Encoder/Encoder.php:158
Implicitly marking parameter $encoding as nullable is deprecated, the explicit nullable type must be used instead

Triggered by:

* PhpMyAdmin\Tests\TwoFactorTest::testApplication
  /home/runner/work/phpmyadmin/phpmyadmin/tests/unit/TwoFactorTest.php:240

24) /home/runner/work/phpmyadmin/phpmyadmin/vendor/bacon/bacon-qr-code/src/Common/ReedSolomonCodec.php:225
Implicitly marking parameter $erasures as nullable is deprecated, the explicit nullable type must be used instead

Triggered by:

* PhpMyAdmin\Tests\TwoFactorTest::testApplication
  /home/runner/work/phpmyadmin/phpmyadmin/tests/unit/TwoFactorTest.php:240
```

**Comment by Chris53897** [comment]
Make it implicit nullable is fine for me. This is the way to go with PHP 7.4

**Comment by kamil-tekiela** [comment]
> Make it implicit nullable is fine for me. This is the way to go with PHP 7.4

Actually, it's since PHP 7.1. Explicit nullability is possible since [PHP 7.1](https://www.php.net/manual/en/migration71.new-features.php), but if your code needs to support PHP 7.0, you'd have to sick with implicit nullability or no types at all.

**Pull request merged**
