### PR TITLE
feat: allow PHPUnit 10

### PR DESCRIPTION
**Pull request by Chris53897**
allow "spatie/phpunit-snapshot-assertions" 5

### CODE REVIEW

**Comment by Chris53897** [comment]
PHPUnit 11 support could be provided with a seperate configuration file with the migrated configuration.
CI needs to be adjusted to read the correct file.
I think it is not wort the effort right now.

**Comment by DASPRiD** [comment]
Is there actually any reason to not rely on PHPUnit 11 specifically and ignore all older versions? This is a dev dependency afterall.

**Comment by Chris53897** [comment]
The lowest supported PHP Version is 7.1 "php": "^7.1 || ^8.0",
We need to support PHPUnit 7 until the PHP Min Version is bumped.
https://packagist.org/packages/phpunit/phpunit#7.5.20

**Comment by DASPRiD** [comment]
Ah yeah, that makes sense. I wonder if it's safe by now to drop PHP 7 (and 8.0), since those have been EOL for some time. Of course, that'd mean bumping our major version to 3.

**Comment by Chris53897** [comment]
I am in favor of dropping older PHP versions. Min Version PHP  ^8.1 ?
https://www.php.net/supported-versions.php

Do your want to work on this, or should i?

**Comment by DASPRiD** [comment]
Feel free to go ahead!

**Comment by Chris53897** [comment]
I am working on it

**Pull request closed without merging**
