### PR TITLE
Eye rotation doesn't work with inherited colors

### LINKED ISSUE #105: Eye rotation doesn't work with inherited colors
In `drawEye()` rotation will be ignored if `inheritsBothColors()` `inheritsExternalColor()` or `inheritsInternalColor()` return `true`.

Not sure what the best solution is, open to suggestions.

### PR DESCRIPTION
**Pull request by mustanggb**
Fixes #105.

### CODE REVIEW

**Comment by mustanggb** [comment]
If you want a test is it okay to add my non-symmetrical eye interface to the codebase?

**Comment by mustanggb** [comment]
No idea why the test is failing, is there anyway to see the file generated by the CI?

**Comment by mustanggb** [comment]
Okay, figured it out.

The code was fine and the files were identical to the human eye.

Just slight differences probably due to imagick version differences between my system and the test platform.

So I extracted the files from a workflow artifact and now the tests pass.

**Comment by DASPRiD** [comment]
An alternative would be to test with the SVG renderer, since that output is predictable.

**Comment by mustanggb** [comment]
Yup, definitely a safer option, but perhaps better as a follow-up to update all the integration tests.

**Comment by mustanggb** [comment]
@DASPRiD Any feedback, or things you'd like addressed?

**Comment by DASPRiD** [comment]
Generally this looks good to me. I'm not sure about the `GridEye` naming, that's not very descriptive for what it actually is. I cannot think of a better term from the top of my head right now though.

**Comment by DASPRiD** [comment]
How about you rename it to `PointyEye`, I think that might be more descriptive. Apart from that, the PR looks good to me.

**Comment by DASPRiD** [comment]
@mustanggb I haven't heard back from you ever. I'm currently preparing a new major release. If I don't hear back from you in the next few days, I'm going to close this PR.

**Comment by mustanggb** [comment]
Heard back about what?

I was just waiting for it to be merged.

**Comment by DASPRiD** [comment]
@mustanggb See my comments from March 14 and 27, 2022 :)

**Comment by DASPRiD** [comment]
Also, please rebase against the new main branch.

**Comment by mustanggb** [comment]
Just a rename then, I don't mind it.

Rename and rebase at #174.

**Pull request closed without merging**
