### PR TITLE
Fix appendKanjiBytes function

### LINKED ISSUE #123: Something wrong with appendKanjiBytes function?
After I fix Shift-JIS handling in `inOnlyDoubleByteKanji` function with [this PR](https://github.com/Bacon/BaconQrCode/pull/122), `appendKanjiBytes` function starts throwing an error every time I pass Double Byte Kanji Character string.

For example: 
"日本", "こんにちは" -> error // Only Double Bytes Shift-JIS
"日本123", "こんにちはhellow" -> OK // Double Bytes Shift-JIS and ASCII works fine

Details in [https://github.com/Bacon/BaconQrCode/pull/122#issuecomment-1397920451](https://github.com/Bacon/BaconQrCode/pull/122#issuecomment-1397920451)

213619290-b544f094-b19e-4cf7-a77c-068847a6364b

### PR DESCRIPTION
**Pull request by askdkc**
This fix will close #123

### CODE REVIEW

**Comment by DASPRiD** [comment]
@askdkc Please have a look at the failing tests.

**Comment by askdkc** [comment]
@DASPRiD 

You need to update the test. Please merge this PR https://github.com/Bacon/BaconQrCode/pull/145 to this branch and run the test again.

**Comment by DASPRiD** [comment]
Hmmm, I'm not sure why that other PR would be needed. The input to the function should be UTF-8.

**Comment by DASPRiD** [comment]
Ignore what I said, I see that you did the opposite of what I thought :D

**Comment by DASPRiD** [comment]
Can you fix the linting errors? Then I can merge it.

**Comment by askdkc** [comment]
@DASPRiD 

Linting Error Fix: https://github.com/Bacon/BaconQrCode/pull/146

**Comment by askdkc** [comment]
@DASPRiD 

My bad. Somehow I lost write access to this PR.

**Pull request closed without merging**
