### PR TITLE
ci: Add tests for PHP 8.4

### PR DESCRIPTION
**Pull request by Chris53897**

### CODE REVIEW

**Comment by DASPRiD** [comment]
Hm, this did cause some issues in the main CI tests:

https://github.com/Bacon/BaconQrCode/actions/runs/11218336744

**Comment by Chris53897** [comment]
Yes. This PR did not run the PHP 8.4 check. I do not know why.
The PHP 8.4 run fails because of https://github.com/Bacon/BaconQrCode/actions/runs/11218336744/job/31181897708#step:6:24

**Comment by Chris53897** [comment]
I think we need to wait for 
https://github.com/laminas/laminas-stdlib/pull/118

**Comment by melroy89** [comment]
It's implemented in: https://github.com/laminas/laminas-stdlib/pull/119

**Pull request merged**
