### PR TITLE
Fix Shift JIS support

### PR DESCRIPTION
**Pull request by askdkc**
This PR is a fix for the issue #123

### CODE REVIEW

**Comment by askdkc** [comment]
@DASPRiD 

I have no idea which part is causing the Lint error (no logs it seems).
If you can show me where to fix, I'm happy to do that.

**Comment by DASPRiD** [comment]
@askdkc There are logs, it's about non-required use of double quotes instead of single quotes, click on the details.

**Comment by askdkc** [comment]
@DASPRiD 

Thanks! I fixed the lint errors.

**Comment by DASPRiD** [comment]
Whoops, you might have to rebase against the main branch again, I'm sorry :)

**Comment by askdkc** [comment]
@DASPRiD 

OK, I will recreated my PR as #170

**Pull request closed without merging**
